[project]
name = "rss-hydrator"
version = "0.1.0"
description = "Hydrate GitHub commits and Youtube channel feeds"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "flask>=3.0.3",
    "lxml>=5.3.0",
    "requests>=2.32.3",
]
